/**
 * Synthetic upload fixtures for end-to-end tests.
 *
 * Generated bytes only — no real document ever enters the test suite
 * (docs/privacy/data-classification.md: real letters must never appear in
 * development, tests, or staging).
 */

/** Real 1×1 pixel PNG. */
export const PNG_BYTES = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "base64",
);

/** Minimal single-page PDF skeleton. */
export const PDF_BYTES = Buffer.from(
  "%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n" +
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n" +
    "3 0 obj\n<< /Type /Page /Parent 2 0 R >>\nendobj\n" +
    "trailer\n<< /Root 1 0 R >>\n%%EOF",
  "latin1",
);

/** Plain text — must be rejected by the client-side pre-check. */
export const TEXT_BYTES = Buffer.from("Sehr geehrte Damen und Herren", "utf8");
