import AxeBuilder from "@axe-core/playwright";
import { expect, test, type Page } from "@playwright/test";
import { PDF_BYTES, PNG_BYTES, TEXT_BYTES } from "./fixtures";

/**
 * End-to-end coverage of the upload pipeline against the real API running
 * the stub provider — no AI, no cost, fully deterministic.
 */

async function expectNoSeriousA11yViolations(page: Page) {
  const results = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"])
    .analyze();
  const serious = results.violations.filter(
    (v) => v.impact === "serious" || v.impact === "critical",
  );
  expect(serious, JSON.stringify(serious, null, 2)).toEqual([]);
}

test.describe("upload flow — English", () => {
  test("uploads a letter and shows the explanation with evidence", async ({ page }) => {
    await page.goto("/en/upload/");

    await page.setInputFiles("#letter-file", {
      name: "letter.png",
      mimeType: "image/png",
      buffer: PNG_BYTES,
    });
    // The chosen filename is echoed back so the user can confirm it.
    await expect(page.getByText("letter.png")).toBeVisible();

    await page.getByRole("button", { name: "Explain this letter" }).click();

    // Result appears with the normalized deadline from the stub analysis.
    await expect(page.getByRole("heading", { name: "What this letter says" })).toBeVisible({
      // Generous: desktop and mobile projects run in parallel against one dev
      // server, so first-paint of a route can queue behind a compile.
      timeout: 30_000,
    });
    await expect(page.getByText("2026-08-15")).toBeVisible();
    await expect(page.getByText("Jobcenter Berlin Mitte").first()).toBeVisible();

    // Evidence is collapsed by default and reveals the German source text.
    const evidenceToggle = page.getByText("Original German text").first();
    await expect(evidenceToggle).toBeVisible();
    await evidenceToggle.click();
    await expect(page.getByText(/bis zum 15\. August 2026/).first()).toBeVisible();

    // AI transparency is shown with the result, not buried in the terms.
    await expect(page.getByText(/generated by AI and can contain mistakes/)).toBeVisible();

    await expectNoSeriousA11yViolations(page);
  });

  test("reset clears the result and returns to the empty form", async ({ page }) => {
    await page.goto("/en/upload/");
    await page.setInputFiles("#letter-file", {
      name: "letter.pdf",
      mimeType: "application/pdf",
      buffer: PDF_BYTES,
    });
    await page.getByRole("button", { name: "Explain this letter" }).click();
    await expect(page.getByRole("heading", { name: "What this letter says" })).toBeVisible({
      // Generous: desktop and mobile projects run in parallel against one dev
      // server, so first-paint of a route can queue behind a compile.
      timeout: 30_000,
    });

    await page.getByRole("button", { name: "Delete and start over" }).click();

    // Result is gone and the upload control is back.
    await expect(page.getByRole("heading", { name: "What this letter says" })).toHaveCount(0);
    await expect(page.getByText("2026-08-15")).toHaveCount(0);
    await expect(page.locator("#letter-file")).toBeVisible();
  });

  test("rejects an unsupported file type with a friendly message", async ({ page }) => {
    await page.goto("/en/upload/");
    await page.setInputFiles("#letter-file", {
      name: "letter.txt",
      mimeType: "text/plain",
      buffer: TEXT_BYTES,
    });
    // Scoped to <main>: Next.js renders its own route announcer with
    // role="alert" outside the page content.
    await expect(page.locator("main").getByRole("alert")).toContainText(
      "This file type is not supported",
    );
    // The analyze button stays disabled — no dead end, no false hope.
    await expect(page.getByRole("button", { name: "Explain this letter" })).toBeDisabled();
  });

  test("surfaces the server verdict for a spoofed file type", async ({ page }) => {
    await page.goto("/en/upload/");
    // PNG bytes wearing a PDF content type: passes the client pre-check,
    // caught by server-side magic-byte validation.
    await page.setInputFiles("#letter-file", {
      name: "letter.pdf",
      mimeType: "application/pdf",
      buffer: PNG_BYTES,
    });
    await page.getByRole("button", { name: "Explain this letter" }).click();
    await expect(page.locator("main").getByRole("alert")).toContainText("could not be read", {
      // Generous: desktop and mobile projects run in parallel against one dev
      // server, so first-paint of a route can queue behind a compile.
      timeout: 30_000,
    });
  });
});

test.describe("upload flow — Dari (RTL)", () => {
  test("shows the explanation in Dari while German evidence stays LTR", async ({ page }) => {
    await page.goto("/prs/upload/");
    await expect(page.locator("html")).toHaveAttribute("dir", "rtl");

    await page.setInputFiles("#letter-file", {
      name: "letter.png",
      mimeType: "image/png",
      buffer: PNG_BYTES,
    });
    await page.getByRole("button", { name: "این نامه را برایم توضیح بده" }).click();

    await expect(page.getByRole("heading", { name: "در این نامه چه نوشته شده" })).toBeVisible({
      // Generous: desktop and mobile projects run in parallel against one dev
      // server, so first-paint of a route can queue behind a compile.
      timeout: 30_000,
    });

    // The German evidence blocks must remain left-to-right inside RTL layout.
    // Open every disclosure rather than assuming an order — the result view
    // gained sections over time, and which one comes first is presentation,
    // not the property under test.
    const disclosures = page.getByText("متن اصلی آلمانی");
    const count = await disclosures.count();
    for (let index = 0; index < count; index += 1) {
      await disclosures.nth(index).click();
    }

    const quotes = page.locator("blockquote[lang='de']");
    await expect(quotes.first()).toHaveAttribute("dir", "ltr");
    // The deadline's German wording is present somewhere in the evidence.
    await expect(quotes.filter({ hasText: "August 2026" }).first()).toBeVisible();

    await expectNoSeriousA11yViolations(page);
  });
});

test.describe("upload flow — accessibility", () => {
  test("is operable with the keyboard alone", async ({ page }) => {
    await page.goto("/en/upload/");
    await page.setInputFiles("#letter-file", {
      name: "letter.png",
      mimeType: "image/png",
      buffer: PNG_BYTES,
    });

    // Reach the analyze button and activate it without touching the mouse.
    // The button is disabled until the chosen file registers in React state,
    // so wait for that transition first — focusing a disabled button and
    // pressing Enter silently does nothing.
    const analyze = page.getByRole("button", { name: "Explain this letter" });
    await expect(analyze).toBeEnabled();
    await analyze.focus();
    await expect(analyze).toBeFocused();
    await page.keyboard.press("Enter");

    await expect(page.getByRole("heading", { name: "What this letter says" })).toBeVisible({
      // Generous: desktop and mobile projects run in parallel against one dev
      // server, so first-paint of a route can queue behind a compile.
      timeout: 30_000,
    });
  });

  test("announces processing states in a live region", async ({ page }) => {
    await page.goto("/en/upload/");
    // The polite live region exists before any interaction, so assistive
    // technology is already observing it when the state changes.
    await expect(page.locator("[aria-live='polite']")).toHaveCount(1);
  });
});
