/**
 * English message catalog — the source of truth for the message shape.
 * The Dari catalog must satisfy the same `Messages` type; TypeScript fails
 * the build if any key is missing or extra in either language.
 */
export const en = {
  common: {
    appName: "Welcome Deutschland",
    tagline: "Understand your German letters — in your language.",
    continue: "Continue",
    back: "Back",
    languageSwitch: "Change language",
    skipToContent: "Skip to main content",
    themeToDark: "Switch to dark mode",
    themeToLight: "Switch to light mode",
  },
  languageSelect: {
    title: "Choose your language",
    subtitle: "زبان خود را انتخاب کنید",
    hint: "You can change this anytime.",
    continueSaved: "Continue in",
    // This replaces a claim that every language had been reviewed by native
    // speakers. That is no longer true, and on a service about legal deadlines
    // an inaccurate reassurance is worse than an honest caveat.
    comingLater:
      "Only English has been checked by a native speaker so far. The other languages are machine-translated and are being reviewed — the explanation of your letter is still based on the original German, which is always shown alongside it.",
  },
  home: {
    heroTitle: "Got a German letter you don't understand?",
    heroLead:
      "Take a photo of it. We explain what it says, what it asks you to do, and when it's due — in your language, with the original German passages shown as proof.",
    stepsTitle: "How it works",
    steps: [
      {
        title: "Upload your letter",
        text: "Photograph it with your phone or choose a PDF.",
      },
      {
        title: "Read the explanation",
        text: "Who sent it, what it says, deadlines, and what documents it asks for.",
      },
      {
        title: "Check the proof",
        text: "Every conclusion shows the German sentence it comes from.",
      },
      {
        title: "Done — nothing is stored",
        text: "Your letter is deleted after processing. No account needed.",
      },
    ] as ReadonlyArray<{ title: string; text: string }>,
    privacyTitle: "Before you upload — how we treat your letter",
    privacyPoints: [
      "Your letter is analyzed by artificial intelligence (AI).",
      "It is not stored. After processing, it is gone from our systems.",
      "No account, no name, no email is needed.",
      "AI can make mistakes. Always verify important deadlines against the original letter.",
      "This service explains letters. It is not a law firm and does not give legal advice.",
    ] as ReadonlyArray<string>,
    privacyMore: "Read the full privacy notice",
    uploadCta: "Understand my letter",
    seriousTitle: "Some letters need more than an app",
    seriousText:
      "For letters about courts, asylum decisions, deportation, or losing your home, we deliberately stay cautious and point you to qualified human help.",
    mock: {
      letterLabel: "Your letter",
      resultLabel: "Your explanation",
      deadline: "Deadline found",
      deadlineValue: "15 August 2026",
      action: "What it asks",
      actionValue: "Hand in two documents",
      sender: "From",
      senderValue: "Jobcenter Berlin Mitte",
    },
  },
  upload: {
    title: "Upload your letter",
    lead: "Take a photo of the whole page, or choose a PDF. Your letter is analyzed and then deleted — nothing is stored.",
    pickTitle: "Add your letter",
    chooseFile: "Choose a file",
    takePhoto: "Take a photo",
    fileHint: "PDF, JPG, PNG or WebP · up to 15 MB",
    photoTips:
      "Tips for a good photo: lay the letter flat, use good light, and capture the whole page.",
    selectedFile: "Selected file",
    // {n} is replaced with the count — kept as a placeholder so translators
    // can put the number where their language needs it.
    selectedFiles: "{n} files — read together as one letter",
    multiPageNote:
      "These are read together as one letter, in the order shown. Remove a page or add another before you continue.",
    addAnotherFile: "Add another page",
    removeFile: "Remove",
    analyze: "Explain this letter",
    // Live-region messages announced to screen readers during processing.
    stateChecking: "Checking your file…",
    stateUploading: "Sending your letter securely…",
    stateAnalyzing: "Reading your letter…",
    stateDone: "Your explanation is ready.",
    processingNote: "This usually takes less than a minute. Please keep this page open.",
    resultTitle: "What this letter says",
    from: "From",
    documentType: "Type of letter",
    deadlineTitle: "Deadline",
    originalGerman: "Original German text",
    actionsTitle: "What you are asked to do",
    documentsTitle: "Documents requested",
    nextStepsTitle: "Possible next steps",
    basisDocument: "From the letter",
    basisGeneral: "General advice",
    aiNotice:
      "This explanation was generated by AI and can contain mistakes. The original German letter is the document that counts. For serious matters, get help from a qualified person.",
    startOver: "Delete and start over",
    deletedConfirm: "Your letter and its explanation have been removed from this page.",
    // Extra result sections
    consequencesTitle: "What the letter says happens",
    contactTitle: "Contact details from the letter",
    limitationsTitle: "What this explanation cannot tell you",
    seriousTitle: "This letter looks serious",
    seriousLead: "For a letter like this, please get help from a qualified person.",
    helpCategoriesTitle: "Where to get help",
    // Follow-up questions
    askTitle: "Ask about this letter",
    askLead:
      "Ask anything you want to understand better. Answers come only from what your letter says.",
    askPlaceholder: "For example: what exactly do I have to send?",
    askButton: "Ask",
    askThinking: "Reading your letter…",
    askNotInLetter: "Your letter does not answer this",
    askOutOfScope: "This needs a qualified person",
    askEmptyHint: "Type a question first.",
    askYourQuestion: "You asked",
    askAnswerLabel: "Answer",
    // Error messages, keyed by the API's stable error codes.
    errorTitle: "That did not work",
    errors: {
      FILE_TOO_LARGE: "This file is too big. Please use a file smaller than 15 MB.",
      UNSUPPORTED_TYPE: "This file type is not supported. Please upload a PDF, JPG, PNG or WebP.",
      CORRUPT_FILE: "This file could not be read. Please try taking a new photo.",
      TOO_MANY_PAGES: "This document has too many pages. Please upload the relevant pages only.",
      TOO_MANY_FILES: "That is more files than we can read at once. Please send fewer pages.",
      IMAGE_TOO_LARGE: "This image is too large. Please take a photo with a lower resolution.",
      INVALID_LANGUAGE: "Something went wrong with the language setting. Please reload the page.",
      NO_FILE: "No file was received. Please choose a file and try again.",
      RATE_LIMITED: "Too many requests right now. Please wait a minute and try again.",
      PROVIDER_ERROR: "The analysis service is not available right now. Please try again shortly.",
      // Not a malfunction: this document could not be handled automatically.
      // Trying again will not help, so the advice has to be different.
      ANALYSIS_REFUSED:
        "We could not analyse this letter automatically. This can happen with letters about legal or official proceedings. Please ask a qualified person to look at it — a migration counselling service or a lawyer.",
      INTERNAL_ERROR: "Something went wrong on our side. Please try again.",
      NETWORK: "We could not reach the service. Please check your internet connection.",
    },
    tryAgain: "Try again",
    // Reached only when a build has no API origin configured, which is a
    // deployment fault rather than a stage of the product.
    unavailableTitle: "Uploading is temporarily unavailable",
    unavailableText:
      "We cannot reach the analysis service from here right now. Please try again shortly.",
  },
  privacyPage: {
    title: "Privacy Notice",
    draftBadge: "Draft — pending professional legal review",
    intro:
      "This page explains, in plain language, what happens to your data when you use Welcome Deutschland. The short version: we designed this service so that we know as little about you as possible.",
    sections: [
      {
        heading: "Your letter",
        body: "Your uploaded letter is processed only to create your explanation. We hold it in memory for the few seconds the analysis takes and then discard it. We do not save it to disk, we keep no copy, and we cannot retrieve it afterwards — not even if you ask us to.",
      },
      {
        heading: "The AI service we use",
        body: "To read your letter we send it to Google's Gemini AI service. This means the content of your letter leaves our systems and is handled by Google under their terms. We currently use a free service tier, and under Google's terms content sent on that tier may be retained and used to improve their models. We are working towards a paid agreement that excludes this. Until then, please take this into account for letters you consider especially sensitive.",
      },
      {
        heading: "No account, no profile",
        body: "You do not create an account. We do not build a profile of you. We do not know who you are.",
      },
      {
        heading: "What we do record",
        body: "Anonymous technical information needed to run the service safely: for example that a request happened, how long it took, its rough file size, and whether it succeeded. This never includes your letter's content, your name, or your address.",
      },
      {
        heading: "Your language choice",
        body: "Your selected language is saved only in your own browser, so the site opens in your language next time. It is not sent to us.",
      },
      {
        // Rewritten when advertising was introduced. The previous version said
        // "no advertising", which stopped being true — and a privacy notice
        // that overstates protection is worse than one that admits a limit.
        heading: "Advertising and tracking",
        body: "We ask before showing any ads. If you say no, no advertising code is loaded at all — not hidden, not delayed, simply never requested. If you say yes, ads are served by Google and use cookies. Either way: your letters are never used for advertising, never shared with advertisers, and never stored. There are no analytics scripts following you and no session recording.",
      },
      {
        heading: "Questions and rights",
        body: "You have rights under the EU General Data Protection Regulation (GDPR), including access and erasure. Because we store no documents and no accounts, there is usually nothing we could look up about you — but you can always contact us.",
      },
    ] as ReadonlyArray<{ heading: string; body: string }>,
  },
  termsPage: {
    title: "Terms of Use & Disclaimer",
    draftBadge: "Draft — pending professional legal review",
    sections: [
      {
        heading: "What this service is",
        body: "Welcome Deutschland helps you understand the content of German administrative letters. It gives you an AI-generated explanation for information purposes.",
      },
      {
        heading: "What this service is not",
        body: "It is not a law firm, not a public authority, and not legal advice. It does not decide your rights, predict outcomes, or replace qualified legal, migration, tax, or social counseling.",
      },
      {
        heading: "AI can make mistakes",
        body: "The explanation is generated by artificial intelligence. It can misread documents, especially poor-quality photos. The original German letter always remains the authoritative document. Verify important deadlines and seek qualified help for serious matters.",
      },
      {
        heading: "Your responsibility",
        body: "Only upload documents you are allowed to upload. Do not rely on this service as your only source for decisions with legal consequences.",
      },
    ] as ReadonlyArray<{ heading: string; body: string }>,
  },
  aiPage: {
    title: "How the AI works — transparency",
    intro:
      "You have a right to know how this service produces its explanations. This page keeps it honest and short.",
    points: [
      "Your letter is read by a large language model (AI) operated by our contracted provider.",
      "The AI is instructed to only report what the letter actually says, to show the German text supporting each conclusion, and to say clearly when something is uncertain.",
      "The AI is instructed to never give legal conclusions and to flag serious letters for qualified human help.",
      "Despite these safeguards, AI can misunderstand text. Treat the result as a well-prepared explanation, not as a certified translation or advice.",
      // Was "Your letter is not used to train any AI model." That directly
      // contradicted the privacy notice, which states the current free tier
      // may retain and train on content. Two pages disagreeing about the one
      // question a reader most needs answered is worse than an awkward truth.
      "We do not store your letter and never use it to train anything ourselves. The AI provider is a separate matter: on the free tier we currently use, their terms allow them to retain content and improve their models with it. The privacy notice explains this in full.",
    ] as ReadonlyArray<string>,
  },
  impressumPage: {
    title: "Impressum",
    placeholder:
      "Legal provider identification (Impressum) will be published here before public launch, as required by German law (§ 5 DDG).",
    legalBasis: "Provider identification under § 5 DDG (Digitale-Dienste-Gesetz).",
  },
  donate: {
    label: "Support this site",
    // Says what the money is for and, just as importantly, what it is not for.
    // Someone reading a deportation notice must never wonder whether paying
    // gets them a better answer.
    note: "This service is free and stays free. Donations help pay for it — they change nothing about your letter or the answer you get.",
  },
  guidesPage: {
    title: "Common German letters, explained",
    lead: "These explain what each kind of letter is and what it usually asks for. They are general explanations, not advice about your own case.",
  },
  consent: {
    title: "Can we show ads on this site?",
    body: "Ads help pay for this service. They come from Google and use cookies. Your letters are never used for ads, are never sent to advertisers, and are never stored — that does not change either way. You can say no and everything keeps working exactly the same.",
    accept: "Yes, allow ads",
    reject: "No, no ads",
    more: "Read what we do with your data",
  },
  footer: {
    guides: "Letter guides",
    privacy: "Privacy",
    terms: "Terms & Disclaimer",
    ai: "About the AI",
    impressum: "Impressum",
    notLegalAdvice: "Information only — not legal advice.",
  },
};

/**
 * Structural type all catalogs must match exactly. Derived from the English
 * catalog WITHOUT `as const`, so values are `string` (translatable) while the
 * key structure stays strictly enforced.
 */
export type Messages = typeof en;
